### PR TITLE
Fix KeyError for custom units

### LINKED ISSUE #2: Hartree units?
Passing `u"eV"` and `u"Ry"` seems to work fine, but `u"Ha"` does not appear to work for some reason, even though I do see that Ha is defined in the source.

```julia
julia> get_nist_data("W Mg-like", u"Ha")
ERROR: KeyError: key :Rydberg not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] basefactor at /home/mortenpi/.julia/packages/Unitful/MlDo0/src/units.jl:223 [inlined]
 [3] map at ./tuple.jl:162 [inlined]
 [4] basefactor(::Unitful.FreeUnits{(Unitful.Unit{:Rydberg,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}) at /home/mortenpi/.julia/packages/Unitful/MlDo0/src/units.jl:226
 [5] #s30#135 at /home/mortenpi/.julia/packages/Unitful/MlDo0/src/conversion.jl:50 [inlined]
 [6] #s30#135(::Any, ::Any, ::Any) at ./none:0
 [7] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:506
 [8] uconvert(::Unitful.FreeUnits{(Unitful.Unit{:Hartree,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}, ::Quantity{Float64,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))},Unitful.FreeUnits{(Unitful.Unit{:Rydberg,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}}) at /home/mortenpi/.julia/packages/Unitful/MlDo0/src/conversion.jl:21
 [9] FreeUnits at /home/mortenpi/.julia/packages/Unitful/MlDo0/src/types.jl:78 [inlined]
 [10] |> at ./operators.jl:813 [inlined]
 [11] (::getfield(AtomicData, Symbol("##3#4")){Unitful.FreeUnits{(Unitful.Unit{:Hartree,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}})(::String) at /home/mortenpi/Julia/test/atomicdata/dev/AtomicData/src/AtomicData.jl:43
 [12] iterate at ./generator.jl:47 [inlined]
 [13] _collect(::Array{Union{Missing, String},1}, ::Base.Generator{Array{Union{Missing, String},1},getfield(AtomicData, Symbol("##3#4")){Unitful.FreeUnits{(Unitful.Unit{:Hartree,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}}}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at ./array.jl:632
 [14] map at ./array.jl:561 [inlined]
 [15] parse_eng(::Array{Union{Missing, String},1}, ::Unitful.FreeUnits{(Unitful.Unit{:Hartree,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}) at /home/mortenpi/Julia/test/atomicdata/dev/AtomicData/src/AtomicData.jl:36
 [16] get_nist_data(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Unitful.FreeUnits{(Unitful.Unit{:Hartree,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}) at /home/mortenpi/Julia/test/atomicdata/dev/AtomicData/src/AtomicData.jl:70
 [17] |> at /home/mortenpi/Julia/test/atomicdata/dev/AtomicData/src/AtomicData.jl:84 [inlined]
 [18] get_nist_data(::String, ::Unitful.FreeUnits{(Unitful.Unit{:Hartree,Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1), Unitful.Dimension{:Mass}(1//1), Unitful.Dimension{:Time}(-2//1))}}) at /home/mortenpi/Julia/test/atomicdata/dev/AtomicData/src/AtomicData.jl:84
 [19] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by mortenpi**
I ran into the same error as in #2 and I think I figured out how to get around it.

Fixes #2.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -2,6 +2,11 @@ using AtomicData
 using Test
 using Unitful
 
+@testset "Units" begin
+    @test isa(u"Ha", Unitful.FreeUnits)
+    @test isa(u"Ry", Unitful.FreeUnits)
+end
+
 @testset "Simple queries" begin
     for unit in [u"cm^-1", u"eV", u"Ry"]
```
Comment (jagot) [inline test/runtests.jl]: Could you also add `u"Ha"` here?

Comment (mortenpi) [reply test/runtests.jl]:
```suggestion
    for unit in [u"cm^-1", u"eV", u"Ry", u"Ha"]
```

**Comment by jagot** [comment]
Thanks!
